### ISSUE TITLE
Distinction between a "service" and "managed services"

### ISSUE THREAD

**Issue by morgante** [getsentry/fsl.software#24]
I'm exploring using the FSL and am interested in how people have considered the distinction between a competing service and a permitted managed service.

Specifically, what is the line between "a product or service that offers the same or substantially similar functionality to the Software" and "in connection with software development services or managed services that you provide to a licensee using the Software in accordance with these Terms and Conditions."

If a managed services provider / agency provides professional services that *effectively* replace the need to pay for the commercial offering, how do people navigate that?

SemGrep has navigated a [similar problem](https://semgrep.dev/docs/faq/#im-a-security-professional-do-i-have-to-pay-for-semgrep) through the [Commons Clause](https://github.com/semgrep/semgrep-rules/blob/develop/LICENSE):

> For purposes of the foregoing, “Sell” means practicing any or all of the rights granted to you under the License to provide to third parties, for a fee or other consideration (including without limitation fees for hosting or consulting/ support services related to the Software), a product or service whose value derives, entirely or substantially, from the functionality of the Software. Any license notice or attribution required by the License must also include this Commons Clause License Condition notice.

**Comment by chadwhitacre** [comment]
Thanks @morgante, added to https://github.com/getsentry/fsl.software/issues/23.

Thoughts @gavin-zee @hmeeker et al.?

**Comment by hmeeker** [comment]
I would say, as an example, that if you develop an e-commerce application, and the software being licensed is a database, that is not competing, because an e-commerce application is not a commercial substitute for a database. In other words, not "same or substantially similar functionality." It's no accident that Commons Clause was originally written with a view to licensing infrastructure software like database platforms.

**Comment by gavin-zee** [comment]
I tend to think of this from the perspective of the user of the software.

Using Sentry as an example, if a user wanted to self-host Sentry under the FSL to monitor their applications, that would be permitted. If that same user wanted a MSP to host the software on the user's behalf, that doesn't fundamentally change the intended permitted use of the software under the FSL.

Differentiate that from the MSP deciding that they wanted to sell error monitoring services using the software and offering it to the market en masse - a competing use.

**Comment by cwinters8** [comment]
I came here with a similar thought/question to @morgante's. If an MSP can sell the configuration and hosting of my software, this effectively replaces my paid offering of the software, even if they would have to do this for every customer who wants it. They could simply offer "hosting services for XYZ" and this would not be substantially different than signing up for my service directly.

I have two early stage projects that I would like to eventually license under the FSL, because the FSL seems to align better with my purpose better than the BSL or more traditional open source licenses. I'm not sure I would really feel comfortable with [this specific clause](https://github.com/getsentry/fsl.software/blob/5b65dc0cacc0acb769f6782aaa6c6d78a4b79465/FSL-1.0-MIT.template.md?plain=1#L54-L56C16) though.

To be clear I think the FSL is overall a really great idea and I'm glad y'all are making it happen 🚀

**Comment by chadwhitacre** [comment]
Hey @morgante @cwinters8, I had a call today with @hmeeker and @gavin-zee as part of #23, and we talked about this question. Ultimately, our design decision for FSL is to allow professional services. We recognize this is a bit of a gray area and may be a deal-breaker for some folks. Unfortunately it's hard to completely avoid all edge cases like this, and so what we've done on #32 is to simply the language a bit but otherwise leave it to each adopter to interpret as best fits their situation. @hmeeker and @gavin-zee have provided some of the intent behind our interpretation above.

Here's what we intend to move forward with on #32:

> Permitted Purposes specifically include using the Software:
> [...]
> 4. in connection with professional services that you provide to a licensee using the Software in accordance with these Terms and Conditions.

Note that the license is with the company hiring the professional services consultant, not with the consultant. If/when we see wider adoption maybe we can revisit if clearer patterns emerge.

Thanks for bringing this up.

**Comment by morgante** [comment]
Thanks for the update. I do think the new language is clearer, so that's a good outcome.

For our purposes, I unfortunately think FSL might not be a good fit because of this. Our main competition is from consultants/professional services, so the restrictions the FSL provides don't seem to meaningfully protect our business position especially relative to the benefits of going fully open source.

**Comment by chadwhitacre** [comment]
Ah, well. Thanks for closing the loop. Best of luck, @morgante!

**Comment by cwinters8** [comment]
This fixes the issue for my case. Thank you for putting so much thought into it! I think the language is much clearer now.

**Comment by chadwhitacre** [comment]
50/50. I'll take it. :-)

Cheers! 🍻
