### ISSUE TITLE
Clarify licensing of external contributions

### ISSUE THREAD

**Issue by rsteube** [getsentry/fsl.software#37]
So according to [this](https://github.com/gitbutlerapp/gitbutler/blob/master/CONTRIBUTING.md#understand-the-license) external contributions would implicitly be licensed under the `FSL`.
But what if one decides at one point to fully switch to `MIT` or `Apache-2.0`, doesn't the 2 year delay then apply for the owner as well?

**Comment by gavin-zee** [comment]
@rsteube contributions would likely need to be made under a separate contribution license agreement that grants the owner broad rights to re-license the contribution (under FSL or otherwise) to avoid the conflict you mention above. We would recommend setting up a separate contribution license for FSL licensed projects rather than relying on license-out=license-in.
