### ISSUE TITLE
Why does FSL forbids commercial education?

### ISSUE THREAD

**Issue by baptisteArno** [getsentry/fsl.software#50]
It seems clear when reading the license that it forbids people to create monetized content about the project

> Permitted Purposes specifically include using the Software:
> 
> for your internal use and access;
> 
> **for non-commercial education;**
> 
> for non-commercial research; and

I am actually fine with people educating the market with paid courses for example even if he self-hosts the project.

So I am wondering why you think commercial education is part of "competing use". Or maybe I am not getting this restriction right?

Also, If I want to allow this, is removing that particular line enough?

**Comment by chadwhitacre** [comment]
@gavin-zee @heathermeeker @hmeeker Do you remember the intent behind this one? Feels to me like it's open to interpretation and providing educational content about a product could be construed as permitted.

@baptisteArno Do you have a specific need for this right now or is your question theoretical or ... ?

**Comment by baptisteArno** [comment]
Can I simply remove this line and still name the license FSL and say that my project is licensed under FSL?

**Comment by chadwhitacre** [comment]
> Can I simply remove this line and still name the license FSL and say that my project is licensed under FSL?

No. Only the text as written is the FSL-1.1.

Why are you so concerned about this? Do you have a real-world use case?

**Comment by baptisteArno** [comment]
I am curious to know why these `Permitted Purposes` examples exist. What would happen if this section is removed?

**Comment by chadwhitacre** [comment]
Some clarification from internal conversation:

> Non-commercial education (I.e. using the software to teach a class in university) is always permitted. Building a paid course around a piece of software might be a competing use depending on whether the licensor offers its own paid content around the software

I don't see anything about paid content on typebot.io/pricing, so that's one signal that you are fine with third-party commercial content. I don't see that you explicitly promote such content on typebot.io, that would probably be an even stronger signal that you welcome this kind of thing. You can always be explicit about it in an FAQ about your licensing, if you do decide to adopt FSL.

> **Am I allowed to sell educational content about Typebot?**
>
> Yes! Typebot's business model is based on hosting, not on selling educational content. Therefore we do not consider this to be competition. In fact, we welcome it!

Would something along those lines work for you?

**Comment by voxpelli** [comment]
`Non-commercial` is a problematic phrase, eg. [Charter Schools](https://en.wikipedia.org/wiki/Charter_school) in Sweden are government funded but can be operated on both a non-profit and for-profit basis – is a for-profit Charter School non-commercial?

Creative Commons explicitly [define what `non-commercial`](https://wiki.creativecommons.org/wiki/NonCommercial_interpretation) means in their licenses, but still face problems. Their definition:

> NonCommercial means not primarily intended for or directed towards commercial advantage or monetary compensation.

If the `Permitted Purposes specifically include using the Software:` is purely explanatory, then it belongs in an FAQ and not the license. If its actually extending the permitted use as defined in the generic definition, then it should define what `non-commercial` means (and maybe also what `education` and `research` means)

**Comment by baptisteArno** [comment]
> If the `Permitted Purposes specifically include using the Software:` is purely explanatory, then it belongs in an FAQ and not the license. If its actually extending the permitted use as defined in the generic definition, then it should define what `non-commercial` means (and maybe also what `education` and `research` means)

This!

My point is that I like FSL because it is dead simple to understand. But I feel like this example sections should not be part of the license and it's the owner's job to maybe clarify what can be done in a FAQ.

I think it is impacting people considering joining the Fair source movement. I felt a bit lost as this license part seems too restrictive at first.

**Comment by voxpelli** [comment]
And its kind of weird if eg. Harvard etc are allowed `Competing Use`simply because they are a non-commercial education – why would they need to be allowed `Competing Use`?

**Comment by chadwhitacre** [comment]
We chose the examples of specifically permitted uses based on our experience with Sentry since [adopting BSL in 2019](https://blog.sentry.io/relicensing-sentry/) (predecessor to FSL). We regularly fielded requests from people asking if they are allowed to use Sentry in their particular case, so our intent is to provide direct answers for common cases. All legal language is subject to interpretation, but of course with broader exposure and adoption we should discuss implications as they become newly apparent.

I appreciate that Typebot has a different circumstance with the third-party educational content. The best I can offer today is the idea of [an FAQ as above](https://github.com/getsentry/fsl.software/issues/50#issuecomment-2374421454) to make it clear to your community @baptisteArno that third-party content is not in competition and is in fact highly welcomed. I think it's good that we have this conversation on record, if we hear enough feedback along these lines from others with real-world use cases, we can take that into account, possibly even working some changes into a (theoretical at this point) future version of FSL. I can't really offer to make a change to FSL on the strength of this one instance alone, however, so I am going to close this ticket out. 🙏

**Comment by heathermeeker** [comment]
I can only speak to the general drafting issue and not a specific case, here. Keep in mind this is a template license that potentially covers all sorts of software. That language is necessary because without it, commercial education providers get a free pass. I don't think that's fair. Commercial education is a big sector -- think about ETS or big universities, hospitals, libraries, or other non-profits that potentially have huge revenues and assets. If, for example, you released a CMS or learning platform under this license, you would not want to give that free pass, because that would be your main market demographic. If you released other kinds of software, you might not care so much. 

Note that the license prohibits *using the software* for commercial education, not merely providing education about the software. For software that is not, say, a CMS or learning platform, the restriction might not have much meaning. Any ambiguity about it could be shored up in an FAQ. 

I realize this post may be out of sequence, unfortunately I have not been able to study the whole string.

**Comment by voxpelli** [comment]
@chadwhitacre How about all of the work that Creative Commons did on researching Non-Commercial definitions and consequences? https://wiki.creativecommons.org/wiki/NonCommercial_interpretation Their definition is based on that? I feel that non-commercial is only simple in a context of 501(c)(3) organizations and such, but that's a very US centric approach?

**Comment by voxpelli** [comment]
BSL does not mention `non-commercial`, they only say:

> The Licensor hereby grants you the right to copy, modify, create derivative works, redistribute, and make non-production use of the Licensed Work.

**Comment by chadwhitacre** [comment]
CC's docs on non-commercial are good to have on the table, thanks for surfacing.

**Comment by heathermeeker** [comment]
Creative Commons has in fact not done a lot of work on the commercial/non-commercial distinction. There is only a non-binding wiki that leaves most people confused. Plus CC is not a software license.

**Comment by ezekg** [comment]
As it's been said, I think you should keep in mind that the permitted uses are there to allow them explicitly, even if one somehow "competes" with the author, e.g. internal self-hosting. If somebody providing commercial education for your product is not competing with you (i.e. you're also providing commercial education), then it's an implicit permitted use. That's the beauty of the FSL/FCL — it's very permissive, as long as you're not competing with the author.

If you want to add an FAQ stating that you'll never compete on education, that's fine and may be helpful to some, but likely not even needed imo — it's already allowed, just implicitly,
